config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :articles
  get '/about' => 'articles#about'
  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :find_article, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    
    def index
        if params[:category].blank?
        @articles = Article.all.order("created_at DESC")
        else
        @category_id = Category.find_by(name: params[:category]).id
        @articles = Article.where(category_id: @category_id).order("created_at DESC")
        end
        
    end
    
    def about
    end
    
    def show
    end
    
    def new
        @article = current_user.articles.build
    end

    def create
        @article = current_user.articles.build(article_params)
        if @article.save
        redirect_to @article
        else
        render 'new'
        end
    end
        
    def edit
    end
    
    def update
      if @article.update(article_params)
        redirect_to @article
      else
        render 'edit'
      end
    end
    
    def destroy
        @article.destroy
        redirect_to root_path
    end
    
    private
    
    def find_article
        @article = Article.find(params[:id])
    end
    
    def article_params
        params.require(:article).permit(:title, :content, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= simple_form_for @article do |f|
    = f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a Category"}
    = f.input :title
    = f.input :content
    = f.submit

app/views/articles/about.html.erb
<h1>About</h1>

<p>Wiki was developed with inspiration from Wikipedia. Wiki is a simple app that allows users the ability
to Sign-In and create an article, edit and delete articles, and put articles in catagories.
</p>

app/views/articles/edit.html.haml
%h1 Edit Article

= render 'form'

= link_to "Back", root_path

app/views/articles/index.html.haml
- @articles.each do |article|
  %h2= link_to article.title, article
  %p 
  Published at
  = article.created_at.strftime('%b %d, %Y')
  %p= truncate(article.content, length:200)
  %br
    

app/views/articles/new.html.haml
%h1 New Article

= render 'form'

= link_to "Back", root_path

app/views/articles/show.html.haml
%h1= @article.title 

%p= @article.content 

.btn-group
    = link_to "Back", root_path, class: "btn btn-default"
    - if user_signed_in?
        = link_to "Edit", edit_article_path(@article), class: "btn btn-default"
        = link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default"
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wiki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "Wiki", root_path, class: "navbar-brand" %>
      
      

    </div>
    
  
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <li>
          <% if user_signed_in? %>
          <%= link_to "New Article", new_article_path %>
          <% end %>
        </li>
        <li><%= link_to "Sign In", new_user_registration_path %></li>
    
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
  
</nav>

<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="col-md-8 row">
    <%= yield %>
  </div>
    
  <div class="col-md-4">
    <ul div class="list-group">
      <li> <%= link_to "All Articles", root_path, class: "list-group-item" %> </li>
      <% Category.all.each do |category| %> 
      <li> <%= link_to category.name, articles_path(category: category.name), class: "list-group-item" %> </li>
      <%end%>
    </ul>
   </div>
  </div>
  
</div>

</body>
</html>